name: Benchmark build and run

# Builds the branch benchmark code against Spack-installed dependencies
# for CPU and GPU versions. Runs the CPU version of the branch
# benchmark.

on:
  workflow_call:
    inputs:
      base-image:
        required: true
        type: string
      spack-buildcache:
        required: true
        type: string
      build-device:
        required: true
        type: string
      spack-opt:
        required: true
        type: string

env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v5

      #- if: ${{ inputs.build-device != 'cpu' }}
      #  name: Install GPU compiler/driver
      #  uses: ukri-bench/spack-configs/actions/install-gpu-driver@main
      #  with:
      #    runtime: ${{ inputs.build-device }}

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop     # Spack version (examples: develop, releases/v0.23)
          color: true      # Force color output (SPACK_COLOR=always)
          path: spack-src  # Where to clone Spack

      - name: Get Spack config
        run: |
          wget -O spack.yml https://raw.githubusercontent.com/ukri-bench/spack-configs/refs/heads/main/configs/gh-actions/spack.yml

      - name: Add ukri-bench Spack repository and create environment
        shell: spack-bash {0}
        run: |
          spack repo add --name bench_pkgs https://github.com/ukri-bench/spack-packages.git ./bench_pkgs
          spack mirror add --autopush --unsigned --type binary --oci-username-variable GITHUB_USER  \
            --oci-password-variable GITHUB_TOKEN local-buildcache ${{ inputs.spack-buildcache }}
          spack env create . spack.yml

      - if: ${{ inputs.build-device == 'rocm' }}
        name: Find compilers (ROCm)
        shell: spack-bash {0}
        run: |
          spack -e . compiler find
          spack -e . config get packages

      - if: ${{ inputs.build-device == 'cuda' }}
        name: Install nvhpc
        shell: spack-bash {0}
        run: spack -e . install --add nvhpc+blas+lapack+mpi default_cuda=12.9

      - name: Concretize
        shell: spack-bash {0}
        run: |
          spack -e . add quantum-espresso${{ inputs.spack-opt }}
          spack -e . concretize

      - name: Build Quantum Espresso
        shell: spack-bash {0}
        run: spack -e . install -j 4

      - name: Publish Executable
        shell: spack-bash {0}
        run: |
          spack -e . buildcache push --base-image ${{ inputs.base-image }} \
            --update-index --tag ${{ github.sha }}-${{ inputs.build-device }} local-buildcache