name: Benchmark build and run

# Builds the branch benchmark code against Spack-installed dependencies
# for CPU and GPU versions. Runs the CPU version of the branch
# benchmark.

on:
  # Uncomment the below 'push' to trigger on push
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        backend:
          [
            { device: cpu, spack_opt: "%gcc ^openblas ^fftw"},
            # { device: rocm, spack_opt: "++rocm" },
            # { device: cuda, spack_opt: "++cuda" },
          ]
    uses: ./.github/workflows/build.yml  
    with:
      base-image: ubuntu-24.04
      spack-buildcache: oci://ghcr.io/ukri-bench/spack-buildcache-qe
      build-device: ${{ matrix.backend.device }}
      spack-opt: ${{ matrix.backend.spack_opt }}
      
    permissions:
      packages: write

