name: Benchmark build and run

# Builds the branch benchmark code against Spack-installed dependencies
# for CPU and GPU versions. Runs the CPU version of the branch
# benchmark.

on:
  # Uncomment the below 'push' to trigger on push
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        backend:
          [
            { device: cpu, base-image: ubuntu:24.04, spack-opt: "+mpi%gcc ^openblas ^fftw"},
            { device: cuda, base-image: nvidia/cuda:12.9.1-base-ubuntu24.04, spack-opt: "+mpi+cuda+mpigpu%nvhpc" },
            # { device: rocm, spack_opt: "++rocm" },
          ]
    uses: ./.github/workflows/build.yml  
    with:
      base-image: ${{ matrix.backend.base-image }}
      spack-buildcache: oci://ghcr.io/ukri-bench/spack-buildcache-qe
      build-device: ${{ matrix.backend.device }}
      spack-opt: ${{ matrix.backend.spack-opt }}
    secrets: inherit
    permissions:
      packages: write

